export const COLORS = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#0043F9',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
};

export const Items = [
  {
    id: 1,
    category: 'product',
    productName: 'Cardashan',
    productPrice: 12,
    description: '',
    isOff: true,
    offPercentage: 15,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 2,
    category: 'product',
    productName: 'cartable',
    productPrice: 12,
    description: '',
    isOff: false,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 3,
    category: 'accessory',
    productName: 'Bluetooth',
    productPrice: 12,
    description: '',
    isOff: true,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 4,
    category: 'accessory',
    productName: 'JBl',
    productPrice: 12,
    description: '',
    isOff: false,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 5,
    category: 'accessory',
    productName: 'Bluetooth',
    productPrice: 12,
    description: '',
    isOff: true,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 6,
    category: 'accessory',
    productName: 'printer',
    productPrice: 435,
    description: '',
    isOff: true,
    offPercentage: 12,
    productImage: '',
    isAvailable: false,
    productImageList: [],
  },
];
