export const COLORS = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#0043F9',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
};

export const Items = [
  {
    id: 1,
    category: 'product',
    productName: 'Cardashan',
    productPrice: 12,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus iusto corporis nesciunt illum, accusantium quae delectus veritatis non voluptates animi placeat laboriosam cum quos exercitationem doloremque aut similique laudantium voluptas.',
    isOff: true,
    offPercentage: 15,
    productImage: require('../database/images/prod.jpg'),
    isAvailable: true,
    productImageList: [
      require('../database/images/figma-task.jpg'),
      require('../database/images/gloire.jpg'),
      require('../database/images/prod1.jpg'),
    ],
  },
  {
    id: 2,
    category: 'product',
    productName: 'cartable',
    productPrice: 12,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus iusto corporis nesciunt illum, accusantium quae delectus veritatis non voluptates animi placeat laboriosam cum quos exercitationem doloremque aut similique laudantium voluptas.',
    isOff: false,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 3,
    category: 'accessory',
    productName: 'Bluetooth',
    productPrice: 12,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus iusto corporis nesciunt illum, accusantium quae delectus veritatis non voluptates animi placeat laboriosam cum quos exercitationem doloremque aut similique laudantium voluptas.',
    isOff: true,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 4,
    category: 'accessory',
    productName: 'JBl',
    productPrice: 12,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus iusto corporis nesciunt illum, accusantium quae delectus veritatis non voluptates animi placeat laboriosam cum quos exercitationem doloremque aut similique laudantium voluptas.',
    isOff: false,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 5,
    category: 'accessory',
    productName: 'Bluetooth',
    productPrice: 12,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus iusto corporis nesciunt illum, accusantium quae delectus veritatis non voluptates animi placeat laboriosam cum quos exercitationem doloremque aut similique laudantium voluptas.',
    isOff: true,
    offPercentage: 12,
    productImage: '',
    isAvailable: true,
    productImageList: [],
  },
  {
    id: 6,
    category: 'accessory',
    productName: 'printer',
    productPrice: 435,
    description:
      'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus iusto corporis nesciunt illum, accusantium quae delectus veritatis non voluptates animi placeat laboriosam cum quos exercitationem doloremque aut similique laudantium voluptas.',
    isOff: true,
    offPercentage: 12,
    productImage: '',
    isAvailable: false,
    productImageList: [],
  },
];
